_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/mask_rcnn/mask_rcnn_R_50_FPN_base/model_reset_remove.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 20
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_novel_3shot',)
  TEST: ('coco_test_novel',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (10000,)
  MAX_ITER: 1500
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/coco/mask_rcnn/mask_rcnn_R_50_FPN_ft_novel_3shot"