_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/mask_rcnn/mask_rcnn_R_50_FPN_ft_novel_1shot_combine/model_reset_combine.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 80
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('coco_trainval_all_2shot',)
  TEST: ('coco_test_all',)
SOLVER:
  IMS_PER_BATCH: 16
  # BASE_LR: 0.001
  # STEPS: (28800,)
  # MAX_ITER: 32000
  BASE_LR: 0.005
  MAX_ITER: 4000
  # STEPS: (10000, 15000)
  # MAX_ITER: 20000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 10
OUTPUT_DIR: "checkpoints/coco/mask_rcnn/mask_rcnn_R_50_FPN_ft_all_2shot"