_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  BOX_IOU_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 60
    LOSS_TYPE: 'focal'
    COMBINE_TYPE: 'sigmoid'
    OUTPUT_LAYER: "BoxUncertaintyFastRCNNOutputLayers"
  FREEZE_ALL: True 
  FREEZE_ALL_BUT_BOXES: True
DATASETS:
  TRAIN: ('coco_trainval_base',)
  TEST: ('coco_test_base',)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (10000, 15000)
  MAX_ITER: 20000
  # STEPS: (210000, 250000)
  # MAX_ITER: 270000
OUTPUT_DIR: "checkpoints/coco/mask_rcnn/mask_rcnn_R_50_FPN_base_sigmoid_classifier_box_iou_uncertainty"
